In [8]:
import os

In [9]:
os.getcwd()

'C:\\Users\\Ankita\\Desktop\\ML\\Iris'

In [4]:
import pandas as pd

In [11]:
iris_csv = pd.read_csv('iris.csv')

In [12]:
iris_csv

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
5             5.4          3.9           1.7          0.4     Setosa
6             4.6          3.4           1.4          0.3     Setosa
7             5.0          3.4           1.5          0.2     Setosa
8             4.4          2.9           1.4          0.2     Setosa
9             4.9          3.1           1.5          0.1     Setosa
10            5.4          3.7           1.5          0.2     Setosa
11            4.8          3.4           1.6          0.2     Setosa
12            4.8          3.0           1.4          0.1     Setosa
13            4.3          3.0           1.1          0.1     Setosa
14            5.8          4.0           1.2          0.2     Setosa
15            5.7          4.4           1.5          0.4     Setosa
16            5.4          3.9           1.3          0.4     Setosa
17            5.1          3.5           1.4          0.3     Setosa
18            5.7          3.8           1.7          0.3     Setosa
19            5.1          3.8           1.5          0.3     Setosa
20            5.4          3.4           1.7          0.2     Setosa
21            5.1          3.7           1.5          0.4     Setosa
22            4.6          3.6           1.0          0.2     Setosa
23            5.1          3.3           1.7          0.5     Setosa
24            4.8          3.4           1.9          0.2     Setosa
25            5.0          3.0           1.6          0.2     Setosa
26            5.0          3.4           1.6          0.4     Setosa
27            5.2          3.5           1.5          0.2     Setosa
28            5.2          3.4           1.4          0.2     Setosa
29            4.7          3.2           1.6          0.2     Setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  Virginica
121           5.6          2.8           4.9          2.0  Virginica
122           7.7          2.8           6.7          2.0  Virginica
123           6.3          2.7           4.9          1.8  Virginica
124           6.7          3.3           5.7          2.1  Virginica
125           7.2          3.2           6.0          1.8  Virginica
126           6.2          2.8           4.8          1.8  Virginica
127           6.1          3.0           4.9          1.8  Virginica
128           6.4          2.8           5.6          2.1  Virginica
129           7.2          3.0           5.8          1.6  Virginica
130           7.4          2.8           6.1          1.9  Virginica
131           7.9          3.8           6.4          2.0  Virginica
132           6.4          2.8           5.6          2.2  Virginica
133           6.3          2.8           5.1          1.5  Virginica
134           6.1          2.6           5.6          1.4  Virginica
135           7.7          3.0           6.1          2.3  Virginica
136           6.3          3.4           5.6          2.4  Virginica
137           6.4          3.1           5.5          1.8  Virginica
138           6.0          3.0           4.8          1.8  Virginica
139           6.9          3.1           5.4          2.1  Virginica
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
142           5.8          2.7           5.1          1.9  Virginica
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [21]:
iris_csv.isna()

     sepal.length  sepal.width  petal.length  petal.width  variety
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
5           False        False         False        False    False
6           False        False         False        False    False
7           False        False         False        False    False
8           False        False         False        False    False
9           False        False         False        False    False
10          False        False         False        False    False
11          False        False         False        False    False
12          False        False         False        False    False
13          False        False         False        False    False
14          False        False         False        False    False
15          False        False         False        False    False
16          False        False         False        False    False
17          False        False         False        False    False
18          False        False         False        False    False
19          False        False         False        False    False
20          False        False         False        False    False
21          False        False         False        False    False
22          False        False         False        False    False
23          False        False         False        False    False
24          False        False         False        False    False
25          False        False         False        False    False
26          False        False         False        False    False
27          False        False         False        False    False
28          False        False         False        False    False
29          False        False         False        False    False
..            ...          ...           ...          ...      ...
120         False        False         False        False    False
121         False        False         False        False    False
122         False        False         False        False    False
123         False        False         False        False    False
124         False        False         False        False    False
125         False        False         False        False    False
126         False        False         False        False    False
127         False        False         False        False    False
128         False        False         False        False    False
129         False        False         False        False    False
130         False        False         False        False    False
131         False        False         False        False    False
132         False        False         False        False    False
133         False        False         False        False    False
134         False        False         False        False    False
135         False        False         False        False    False
136         False        False         False        False    False
137         False        False         False        False    False
138         False        False         False        False    False
139         False        False         False        False    False
140         False        False         False        False    False
141         False        False         False        False    False
142         False        False         False        False    False
143         False        False         False        False    False
144         False        False         False        False    False
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [15]:
import xlrd as xl

In [16]:
iris_xlsx = pd.read_excel('iris.xlsx')

In [19]:
iris_xlsx

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
5             5.4          3.9           1.7          0.4     Setosa
6             4.6          3.4           1.4          0.3     Setosa
7             5.0          3.4           1.5          0.2     Setosa
8             4.4          2.9           1.4          0.2     Setosa
9             4.9          3.1           1.5          0.1     Setosa
10            5.4          3.7           1.5          0.2     Setosa
11            4.8          3.4           1.6          0.2     Setosa
12            4.8          3.0           1.4          0.1     Setosa
13            4.3          3.0           1.1          0.1     Setosa
14            5.8          4.0           1.2          0.2     Setosa
15            5.7          4.4           1.5          0.4     Setosa
16            5.4          3.9           1.3          0.4     Setosa
17            5.1          3.5           1.4          0.3     Setosa
18            5.7          3.8           1.7          0.3     Setosa
19            5.1          3.8           1.5          0.3     Setosa
20            5.4          3.4           1.7          0.2     Setosa
21            5.1          3.7           1.5          0.4     Setosa
22            4.6          3.6           1.0          0.2     Setosa
23            5.1          3.3           1.7          0.5     Setosa
24            4.8          3.4           1.9          0.2     Setosa
25            5.0          3.0           1.6          0.2     Setosa
26            5.0          3.4           1.6          0.4     Setosa
27            5.2          3.5           1.5          0.2     Setosa
28            5.2          3.4           1.4          0.2     Setosa
29            4.7          3.2           1.6          0.2     Setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  Virginica
121           5.6          2.8           4.9          2.0  Virginica
122           7.7          2.8           6.7          2.0  Virginica
123           6.3          2.7           4.9          1.8  Virginica
124           6.7          3.3           5.7          2.1  Virginica
125           7.2          3.2           6.0          1.8  Virginica
126           6.2          2.8           4.8          1.8  Virginica
127           6.1          3.0           4.9          1.8  Virginica
128           6.4          2.8           5.6          2.1  Virginica
129           7.2          3.0           5.8          1.6  Virginica
130           7.4          2.8           6.1          1.9  Virginica
131           7.9          3.8           6.4          2.0  Virginica
132           6.4          2.8           5.6          2.2  Virginica
133           6.3          2.8           5.1          1.5  Virginica
134           6.1          2.6           5.6          1.4  Virginica
135           7.7          3.0           6.1          2.3  Virginica
136           6.3          3.4           5.6          2.4  Virginica
137           6.4          3.1           5.5          1.8  Virginica
138           6.0          3.0           4.8          1.8  Virginica
139           6.9          3.1           5.4          2.1  Virginica
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
142           5.8          2.7           5.1          1.9  Virginica
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [34]:
iris_txt = pd.read_table("iris.txt")

C:\Users\Ankita\Python 3.7.2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.

In [36]:
iris_txt

    sepal.length,"sepal.width","petal.length","petal.width","variety"
0                              5.1,3.5,1.4,.2,"Setosa"
1                                4.9,3,1.4,.2,"Setosa"
2                              4.7,3.2,1.3,.2,"Setosa"
3                              4.6,3.1,1.5,.2,"Setosa"
4                                5,3.6,1.4,.2,"Setosa"
5                              5.4,3.9,1.7,.4,"Setosa"
6                              4.6,3.4,1.4,.3,"Setosa"
7                                5,3.4,1.5,.2,"Setosa"
8                              4.4,2.9,1.4,.2,"Setosa"
9                              4.9,3.1,1.5,.1,"Setosa"
10                             5.4,3.7,1.5,.2,"Setosa"
11                             4.8,3.4,1.6,.2,"Setosa"
12                               4.8,3,1.4,.1,"Setosa"
13                               4.3,3,1.1,.1,"Setosa"
14                               5.8,4,1.2,.2,"Setosa"
15                             5.7,4.4,1.5,.4,"Setosa"
16                             5.4,3.9,1.3,.4,"Setosa"
17                             5.1,3.5,1.4,.3,"Setosa"
18                             5.7,3.8,1.7,.3,"Setosa"
19                             5.1,3.8,1.5,.3,"Setosa"
20                             5.4,3.4,1.7,.2,"Setosa"
21                             5.1,3.7,1.5,.4,"Setosa"
22                               4.6,3.6,1,.2,"Setosa"
23                             5.1,3.3,1.7,.5,"Setosa"
24                             4.8,3.4,1.9,.2,"Setosa"
25                                 5,3,1.6,.2,"Setosa"
26                               5,3.4,1.6,.4,"Setosa"
27                             5.2,3.5,1.5,.2,"Setosa"
28                             5.2,3.4,1.4,.2,"Setosa"
29                             4.7,3.2,1.6,.2,"Setosa"
..                                                 ...
120                        6.9,3.2,5.7,2.3,"Virginica"
121                          5.6,2.8,4.9,2,"Virginica"
122                          7.7,2.8,6.7,2,"Virginica"
123                        6.3,2.7,4.9,1.8,"Virginica"
124                        6.7,3.3,5.7,2.1,"Virginica"
125                          7.2,3.2,6,1.8,"Virginica"
126                        6.2,2.8,4.8,1.8,"Virginica"
127                          6.1,3,4.9,1.8,"Virginica"
128                        6.4,2.8,5.6,2.1,"Virginica"
129                          7.2,3,5.8,1.6,"Virginica"
130                        7.4,2.8,6.1,1.9,"Virginica"
131                          7.9,3.8,6.4,2,"Virginica"
132                        6.4,2.8,5.6,2.2,"Virginica"
133                        6.3,2.8,5.1,1.5,"Virginica"
134                        6.1,2.6,5.6,1.4,"Virginica"
135                          7.7,3,6.1,2.3,"Virginica"
136                        6.3,3.4,5.6,2.4,"Virginica"
137                        6.4,3.1,5.5,1.8,"Virginica"
138                            6,3,4.8,1.8,"Virginica"
139                        6.9,3.1,5.4,2.1,"Virginica"
140                        6.7,3.1,5.6,2.4,"Virginica"
141                        6.9,3.1,5.1,2.3,"Virginica"
142                        5.8,2.7,5.1,1.9,"Virginica"
143                        6.8,3.2,5.9,2.3,"Virginica"
144                        6.7,3.3,5.7,2.5,"Virginica"
145                          6.7,3,5.2,2.3,"Virginica"
146                          6.3,2.5,5,1.9,"Virginica"
147                            6.5,3,5.2,2,"Virginica"
148                        6.2,3.4,5.4,2.3,"Virginica"
149                          5.9,3,5.1,1.8,"Virginica"

[150 rows x 1 columns]

In [37]:
iris_txt = pd.read_table("iris.txt", delimiter=",")

C:\Users\Ankita\Python 3.7.2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

In [38]:
iris_txt

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
5             5.4          3.9           1.7          0.4     Setosa
6             4.6          3.4           1.4          0.3     Setosa
7             5.0          3.4           1.5          0.2     Setosa
8             4.4          2.9           1.4          0.2     Setosa
9             4.9          3.1           1.5          0.1     Setosa
10            5.4          3.7           1.5          0.2     Setosa
11            4.8          3.4           1.6          0.2     Setosa
12            4.8          3.0           1.4          0.1     Setosa
13            4.3          3.0           1.1          0.1     Setosa
14            5.8          4.0           1.2          0.2     Setosa
15            5.7          4.4           1.5          0.4     Setosa
16            5.4          3.9           1.3          0.4     Setosa
17            5.1          3.5           1.4          0.3     Setosa
18            5.7          3.8           1.7          0.3     Setosa
19            5.1          3.8           1.5          0.3     Setosa
20            5.4          3.4           1.7          0.2     Setosa
21            5.1          3.7           1.5          0.4     Setosa
22            4.6          3.6           1.0          0.2     Setosa
23            5.1          3.3           1.7          0.5     Setosa
24            4.8          3.4           1.9          0.2     Setosa
25            5.0          3.0           1.6          0.2     Setosa
26            5.0          3.4           1.6          0.4     Setosa
27            5.2          3.5           1.5          0.2     Setosa
28            5.2          3.4           1.4          0.2     Setosa
29            4.7          3.2           1.6          0.2     Setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  Virginica
121           5.6          2.8           4.9          2.0  Virginica
122           7.7          2.8           6.7          2.0  Virginica
123           6.3          2.7           4.9          1.8  Virginica
124           6.7          3.3           5.7          2.1  Virginica
125           7.2          3.2           6.0          1.8  Virginica
126           6.2          2.8           4.8          1.8  Virginica
127           6.1          3.0           4.9          1.8  Virginica
128           6.4          2.8           5.6          2.1  Virginica
129           7.2          3.0           5.8          1.6  Virginica
130           7.4          2.8           6.1          1.9  Virginica
131           7.9          3.8           6.4          2.0  Virginica
132           6.4          2.8           5.6          2.2  Virginica
133           6.3          2.8           5.1          1.5  Virginica
134           6.1          2.6           5.6          1.4  Virginica
135           7.7          3.0           6.1          2.3  Virginica
136           6.3          3.4           5.6          2.4  Virginica
137           6.4          3.1           5.5          1.8  Virginica
138           6.0          3.0           4.8          1.8  Virginica
139           6.9          3.1           5.4          2.1  Virginica
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
142           5.8          2.7           5.1          1.9  Virginica
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

Reading txt file through read_csv() method.

In [41]:
iris_txt = pd.read_csv("iris.txt", delimiter=",")

In [40]:
iris_txt

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
5             5.4          3.9           1.7          0.4     Setosa
6             4.6          3.4           1.4          0.3     Setosa
7             5.0          3.4           1.5          0.2     Setosa
8             4.4          2.9           1.4          0.2     Setosa
9             4.9          3.1           1.5          0.1     Setosa
10            5.4          3.7           1.5          0.2     Setosa
11            4.8          3.4           1.6          0.2     Setosa
12            4.8          3.0           1.4          0.1     Setosa
13            4.3          3.0           1.1          0.1     Setosa
14            5.8          4.0           1.2          0.2     Setosa
15            5.7          4.4           1.5          0.4     Setosa
16            5.4          3.9           1.3          0.4     Setosa
17            5.1          3.5           1.4          0.3     Setosa
18            5.7          3.8           1.7          0.3     Setosa
19            5.1          3.8           1.5          0.3     Setosa
20            5.4          3.4           1.7          0.2     Setosa
21            5.1          3.7           1.5          0.4     Setosa
22            4.6          3.6           1.0          0.2     Setosa
23            5.1          3.3           1.7          0.5     Setosa
24            4.8          3.4           1.9          0.2     Setosa
25            5.0          3.0           1.6          0.2     Setosa
26            5.0          3.4           1.6          0.4     Setosa
27            5.2          3.5           1.5          0.2     Setosa
28            5.2          3.4           1.4          0.2     Setosa
29            4.7          3.2           1.6          0.2     Setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  Virginica
121           5.6          2.8           4.9          2.0  Virginica
122           7.7          2.8           6.7          2.0  Virginica
123           6.3          2.7           4.9          1.8  Virginica
124           6.7          3.3           5.7          2.1  Virginica
125           7.2          3.2           6.0          1.8  Virginica
126           6.2          2.8           4.8          1.8  Virginica
127           6.1          3.0           4.9          1.8  Virginica
128           6.4          2.8           5.6          2.1  Virginica
129           7.2          3.0           5.8          1.6  Virginica
130           7.4          2.8           6.1          1.9  Virginica
131           7.9          3.8           6.4          2.0  Virginica
132           6.4          2.8           5.6          2.2  Virginica
133           6.3          2.8           5.1          1.5  Virginica
134           6.1          2.6           5.6          1.4  Virginica
135           7.7          3.0           6.1          2.3  Virginica
136           6.3          3.4           5.6          2.4  Virginica
137           6.4          3.1           5.5          1.8  Virginica
138           6.0          3.0           4.8          1.8  Virginica
139           6.9          3.1           5.4          2.1  Virginica
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
142           5.8          2.7           5.1          1.9  Virginica
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [42]:
shallow_iris = iris_csv.copy(deep=False)

In [43]:
deep_rirs = iris_csv.copy(deep=True)

In [44]:
iris_csv.index

RangeIndex(start=0, stop=150, step=1)

In [45]:
iris_csv.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [46]:
iris_csv.size

750

In [47]:
iris_csv.shape

(150, 5)

In [48]:
iris_csv.memory_usage()

Index             40
sepal.length    1200
sepal.width     1200
petal.length    1200
petal.width     1200
variety          600
dtype: int64

In [49]:
iris_csv.ndim

2

In [51]:
iris_csv.head(10)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [54]:
iris_csv.tail(6)

     sepal.length  sepal.width  petal.length  petal.width    variety
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [57]:
iris_csv.loc[3]

sepal.length       4.6
sepal.width        3.1
petal.length       1.5
petal.width        0.2
variety         Setosa
Name: 3, dtype: object

In [58]:
iris_csv.iloc[3]

sepal.length       4.6
sepal.width        3.1
petal.length       1.5
petal.width        0.2
variety         Setosa
Name: 3, dtype: object

In [64]:
iris_csv.loc[iris_csv['sepal.length']>5]

     sepal.length  sepal.width  petal.length  petal.width     variety
0             5.1          3.5           1.4          0.2      Setosa
5             5.4          3.9           1.7          0.4      Setosa
10            5.4          3.7           1.5          0.2      Setosa
14            5.8          4.0           1.2          0.2      Setosa
15            5.7          4.4           1.5          0.4      Setosa
16            5.4          3.9           1.3          0.4      Setosa
17            5.1          3.5           1.4          0.3      Setosa
18            5.7          3.8           1.7          0.3      Setosa
19            5.1          3.8           1.5          0.3      Setosa
20            5.4          3.4           1.7          0.2      Setosa
21            5.1          3.7           1.5          0.4      Setosa
23            5.1          3.3           1.7          0.5      Setosa
27            5.2          3.5           1.5          0.2      Setosa
28            5.2          3.4           1.4          0.2      Setosa
31            5.4          3.4           1.5          0.4      Setosa
32            5.2          4.1           1.5          0.1      Setosa
33            5.5          4.2           1.4          0.2      Setosa
36            5.5          3.5           1.3          0.2      Setosa
39            5.1          3.4           1.5          0.2      Setosa
44            5.1          3.8           1.9          0.4      Setosa
46            5.1          3.8           1.6          0.2      Setosa
48            5.3          3.7           1.5          0.2      Setosa
50            7.0          3.2           4.7          1.4  Versicolor
51            6.4          3.2           4.5          1.5  Versicolor
52            6.9          3.1           4.9          1.5  Versicolor
53            5.5          2.3           4.0          1.3  Versicolor
54            6.5          2.8           4.6          1.5  Versicolor
55            5.7          2.8           4.5          1.3  Versicolor
56            6.3          3.3           4.7          1.6  Versicolor
58            6.6          2.9           4.6          1.3  Versicolor
..            ...          ...           ...          ...         ...
120           6.9          3.2           5.7          2.3   Virginica
121           5.6          2.8           4.9          2.0   Virginica
122           7.7          2.8           6.7          2.0   Virginica
123           6.3          2.7           4.9          1.8   Virginica
124           6.7          3.3           5.7          2.1   Virginica
125           7.2          3.2           6.0          1.8   Virginica
126           6.2          2.8           4.8          1.8   Virginica
127           6.1          3.0           4.9          1.8   Virginica
128           6.4          2.8           5.6          2.1   Virginica
129           7.2          3.0           5.8          1.6   Virginica
130           7.4          2.8           6.1          1.9   Virginica
131           7.9          3.8           6.4          2.0   Virginica
132           6.4          2.8           5.6          2.2   Virginica
133           6.3          2.8           5.1          1.5   Virginica
134           6.1          2.6           5.6          1.4   Virginica
135           7.7          3.0           6.1          2.3   Virginica
136           6.3          3.4           5.6          2.4   Virginica
137           6.4          3.1           5.5          1.8   Virginica
138           6.0          3.0           4.8          1.8   Virginica
139           6.9          3.1           5.4          2.1   Virginica
140           6.7          3.1           5.6          2.4   Virginica
141           6.9          3.1           5.1          2.3   Virginica
142           5.8          2.7           5.1          1.9   Virginica
143           6.8          3.2           5.9          2.3   Virginica
144           6.7          3.3           5.7          2.5   Virginica
145           6.7          3.0           5.2          2.3   Virginica
146           6.3          2.5           5.0          1.9   Virginica
147           6.5          3.0           5.2          2.0   Virginica
148           6.2          3.4           5.4          2.3   Virginica
149           5.9          3.0           5.1          1.8   Virginica

[118 rows x 5 columns]

In [71]:
iris_csv.iloc[5:13]

    sepal.length  sepal.width  petal.length  petal.width variety
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa

In [72]:
iris_csv.loc[5:8,['sepal.length','petal.width']]

   sepal.length  petal.width
5           5.4          0.4
6           4.6          0.3
7           5.0          0.2
8           4.4          0.2

In [73]:
iris_csv.at[5,'sepal.length']

5.4

In [74]:
iris_csv.iat[5,2]

1.7

In [75]:
iris_csv.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

In [79]:
iris_csv.select_dtypes(include=[object], exclude=[None])

       variety
0       Setosa
1       Setosa
2       Setosa
3       Setosa
4       Setosa
5       Setosa
6       Setosa
7       Setosa
8       Setosa
9       Setosa
10      Setosa
11      Setosa
12      Setosa
13      Setosa
14      Setosa
15      Setosa
16      Setosa
17      Setosa
18      Setosa
19      Setosa
20      Setosa
21      Setosa
22      Setosa
23      Setosa
24      Setosa
25      Setosa
26      Setosa
27      Setosa
28      Setosa
29      Setosa
..         ...
120  Virginica
121  Virginica
122  Virginica
123  Virginica
124  Virginica
125  Virginica
126  Virginica
127  Virginica
128  Virginica
129  Virginica
130  Virginica
131  Virginica
132  Virginica
133  Virginica
134  Virginica
135  Virginica
136  Virginica
137  Virginica
138  Virginica
139  Virginica
140  Virginica
141  Virginica
142  Virginica
143  Virginica
144  Virginica
145  Virginica
146  Virginica
147  Virginica
148  Virginica
149  Virginica

[150 rows x 1 columns]

In [80]:
iris_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal.length    150 non-null float64
sepal.width     150 non-null float64
petal.length    150 non-null float64
petal.width     150 non-null float64
variety         150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.3+ KB

In [81]:
import numpy as np

In [83]:
np.unique(iris_csv['sepal.length'])

array([4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9])

In [87]:
iris_csv['sepal.length'].astype('object')

0      5.1
1      4.9
2      4.7
3      4.6
4        5
5      5.4
6      4.6
7        5
8      4.4
9      4.9
10     5.4
11     4.8
12     4.8
13     4.3
14     5.8
15     5.7
16     5.4
17     5.1
18     5.7
19     5.1
20     5.4
21     5.1
22     4.6
23     5.1
24     4.8
25       5
26       5
27     5.2
28     5.2
29     4.7
      ...
120    6.9
121    5.6
122    7.7
123    6.3
124    6.7
125    7.2
126    6.2
127    6.1
128    6.4
129    7.2
130    7.4
131    7.9
132    6.4
133    6.3
134    6.1
135    7.7
136    6.3
137    6.4
138      6
139    6.9
140    6.7
141    6.9
142    5.8
143    6.8
144    6.7
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal.length, Length: 150, dtype: object

In [88]:
iris_csv.isnull().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [93]:
cars_data=pd.read_csv("toyota.csv",na_values=["??","????"])

In [94]:
cars_data.isna().sum()

Price        0
Age          0
KM           0
FuelType     0
HP           0
MetColor     0
Automatic    0
CC           0
Doors        0
Weight       0
dtype: int64

In [100]:
pd.crosstab(index=cars_data["FuelType"],columns="count", dropna=True)

col_0     count
FuelType
CNG          17
Diesel      155
Petrol     1264

In [97]:
pd.crosstab(index=cars_data["Doors"], columns=cars_data["FuelType"],dropna=True)

FuelType  CNG  Diesel  Petrol
Doors
2           0       1       1
3           6      61     555
4           3      14     121
5           8      79     587

In [102]:
pd.crosstab(index=cars_data["Automatic"], columns=cars_data["FuelType"],dropna=True)

FuelType   CNG  Diesel  Petrol
Automatic
0           16     155    1185
1            1       0      79

In [103]:
df1=pd.read_csv("crashTest_TrainData.csv")

In [104]:
df2=pd.read_csv("crashTest_TestData.csv")

In [105]:
df1.describe()

         CarID      ManHI      ManBI       IntI      HVACi    Safety
count  80.0000  80.000000  80.000000  77.000000  80.000000  80.00000
mean   40.5000  -0.093500  -0.927750  -0.346623   0.119750   0.54375
std    23.2379   5.802878   5.600224   5.806723   5.813306   5.79723
min     1.0000  -9.930000  -9.940000  -9.990000  -9.820000  -9.80000
25%    20.7500  -5.195000  -5.705000  -5.940000  -5.675000  -4.67750
50%    40.5000   0.635000  -1.815000  -0.500000   0.870000   0.83000
75%    60.2500   5.050000   3.417500   4.820000   5.062500   4.62250
max    80.0000   9.570000   9.610000   9.720000   9.890000   9.99000

In [106]:
df2.describe()

           CarID      ManHI     ManBI       IntI      HVACi     Safety
count   20.00000  20.000000  20.00000  20.000000  20.000000  20.000000
mean    90.50000   0.047000   0.32800   0.524000   0.723500   0.191000
std      5.91608   6.253216   4.05164   4.953771   5.479129   6.154548
min     81.00000  -9.940000  -8.74000  -8.950000  -9.230000  -8.660000
25%     85.75000  -5.535000  -2.50250  -3.272500  -2.455000  -6.095000
50%     90.50000   0.740000   0.67000   1.200000   0.675000  -0.770000
75%     95.25000   5.110000   2.50000   3.907500   5.337500   4.992500
max    100.00000   9.090000   8.42000   8.870000   8.330000   9.620000

In [107]:
df1["CarType"].value_counts()

Hatchback    50
SUV          30
Name: CarType, dtype: int64

In [108]:
df2["CarType"].value_counts()

Hatchback    10
SUV          10
Name: CarType, dtype: int64

In [109]:
df1.isnull().sum()

CarID      0
ManHI      0
ManBI      0
IntI       3
HVACi      0
Safety     0
CarType    0
dtype: int64

In [112]:
df1.isna().sum()

CarID      0
ManHI      0
ManBI      0
IntI       3
HVACi      0
Safety     0
CarType    0
dtype: int64

New Assignment

In [113]:
Train_Data=pd.read_csv("CrashTest_TrainData.csv")

In [114]:
Test_Data=pd.read_csv("CrashTest_TestData.csv")

In [115]:
Train_Data.isnull()

    CarID  ManHI  ManBI   IntI  HVACi  Safety  CarType
0   False  False  False  False  False   False    False
1   False  False  False  False  False   False    False
2   False  False  False  False  False   False    False
3   False  False  False  False  False   False    False
4   False  False  False  False  False   False    False
5   False  False  False  False  False   False    False
6   False  False  False  False  False   False    False
7   False  False  False  False  False   False    False
8   False  False  False  False  False   False    False
9   False  False  False  False  False   False    False
10  False  False  False  False  False   False    False
11  False  False  False  False  False   False    False
12  False  False  False  False  False   False    False
13  False  False  False  False  False   False    False
14  False  False  False   True  False   False    False
15  False  False  False  False  False   False    False
16  False  False  False  False  False   False    False
17  False  False  False  False  False   False    False
18  False  False  False  False  False   False    False
19  False  False  False  False  False   False    False
20  False  False  False  False  False   False    False
21  False  False  False   True  False   False    False
22  False  False  False  False  False   False    False
23  False  False  False  False  False   False    False
24  False  False  False  False  False   False    False
25  False  False  False  False  False   False    False
26  False  False  False  False  False   False    False
27  False  False  False  False  False   False    False
28  False  False  False  False  False   False    False
29  False  False  False  False  False   False    False
..    ...    ...    ...    ...    ...     ...      ...
50  False  False  False  False  False   False    False
51  False  False  False  False  False   False    False
52  False  False  False  False  False   False    False
53  False  False  False  False  False   False    False
54  False  False  False  False  False   False    False
55  False  False  False  False  False   False    False
56  False  False  False  False  False   False    False
57  False  False  False  False  False   False    False
58  False  False  False  False  False   False    False
59  False  False  False  False  False   False    False
60  False  False  False  False  False   False    False
61  False  False  False  False  False   False    False
62  False  False  False  False  False   False    False
63  False  False  False  False  False   False    False
64  False  False  False  False  False   False    False
65  False  False  False  False  False   False    False
66  False  False  False  False  False   False    False
67  False  False  False  False  False   False    False
68  False  False  False  False  False   False    False
69  False  False  False  False  False   False    False
70  False  False  False  False  False   False    False
71  False  False  False  False  False   False    False
72  False  False  False  False  False   False    False
73  False  False  False  False  False   False    False
74  False  False  False  False  False   False    False
75  False  False  False  False  False   False    False
76  False  False  False  False  False   False    False
77  False  False  False  False  False   False    False
78  False  False  False  False  False   False    False
79  False  False  False  False  False   False    False

[80 rows x 7 columns]

In [116]:
Train_Data.isna()

    CarID  ManHI  ManBI   IntI  HVACi  Safety  CarType
0   False  False  False  False  False   False    False
1   False  False  False  False  False   False    False
2   False  False  False  False  False   False    False
3   False  False  False  False  False   False    False
4   False  False  False  False  False   False    False
5   False  False  False  False  False   False    False
6   False  False  False  False  False   False    False
7   False  False  False  False  False   False    False
8   False  False  False  False  False   False    False
9   False  False  False  False  False   False    False
10  False  False  False  False  False   False    False
11  False  False  False  False  False   False    False
12  False  False  False  False  False   False    False
13  False  False  False  False  False   False    False
14  False  False  False   True  False   False    False
15  False  False  False  False  False   False    False
16  False  False  False  False  False   False    False
17  False  False  False  False  False   False    False
18  False  False  False  False  False   False    False
19  False  False  False  False  False   False    False
20  False  False  False  False  False   False    False
21  False  False  False   True  False   False    False
22  False  False  False  False  False   False    False
23  False  False  False  False  False   False    False
24  False  False  False  False  False   False    False
25  False  False  False  False  False   False    False
26  False  False  False  False  False   False    False
27  False  False  False  False  False   False    False
28  False  False  False  False  False   False    False
29  False  False  False  False  False   False    False
..    ...    ...    ...    ...    ...     ...      ...
50  False  False  False  False  False   False    False
51  False  False  False  False  False   False    False
52  False  False  False  False  False   False    False
53  False  False  False  False  False   False    False
54  False  False  False  False  False   False    False
55  False  False  False  False  False   False    False
56  False  False  False  False  False   False    False
57  False  False  False  False  False   False    False
58  False  False  False  False  False   False    False
59  False  False  False  False  False   False    False
60  False  False  False  False  False   False    False
61  False  False  False  False  False   False    False
62  False  False  False  False  False   False    False
63  False  False  False  False  False   False    False
64  False  False  False  False  False   False    False
65  False  False  False  False  False   False    False
66  False  False  False  False  False   False    False
67  False  False  False  False  False   False    False
68  False  False  False  False  False   False    False
69  False  False  False  False  False   False    False
70  False  False  False  False  False   False    False
71  False  False  False  False  False   False    False
72  False  False  False  False  False   False    False
73  False  False  False  False  False   False    False
74  False  False  False  False  False   False    False
75  False  False  False  False  False   False    False
76  False  False  False  False  False   False    False
77  False  False  False  False  False   False    False
78  False  False  False  False  False   False    False
79  False  False  False  False  False   False    False

[80 rows x 7 columns]

In [118]:
import seaborn as sns

In [120]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score

In [121]:
data=Train_Data.copy()

In [122]:
data.describe()

         CarID      ManHI      ManBI       IntI      HVACi    Safety
count  80.0000  80.000000  80.000000  77.000000  80.000000  80.00000
mean   40.5000  -0.093500  -0.927750  -0.346623   0.119750   0.54375
std    23.2379   5.802878   5.600224   5.806723   5.813306   5.79723
min     1.0000  -9.930000  -9.940000  -9.990000  -9.820000  -9.80000
25%    20.7500  -5.195000  -5.705000  -5.940000  -5.675000  -4.67750
50%    40.5000   0.635000  -1.815000  -0.500000   0.870000   0.83000
75%    60.2500   5.050000   3.417500   4.820000   5.062500   4.62250
max    80.0000   9.570000   9.610000   9.720000   9.890000   9.99000

In [131]:
data.describe(include="float")

           ManHI      ManBI       IntI      HVACi    Safety
count  80.000000  80.000000  77.000000  80.000000  80.00000
mean   -0.093500  -0.927750  -0.346623   0.119750   0.54375
std     5.802878   5.600224   5.806723   5.813306   5.79723
min    -9.930000  -9.940000  -9.990000  -9.820000  -9.80000
25%    -5.195000  -5.705000  -5.940000  -5.675000  -4.67750
50%     0.635000  -1.815000  -0.500000   0.870000   0.83000
75%     5.050000   3.417500   4.820000   5.062500   4.62250
max     9.570000   9.610000   9.720000   9.890000   9.99000

In [132]:
data.describe(include="object")

          CarType
count          80
unique          2
top     Hatchback
freq           50

In [184]:
data.describe(include="O")

          CarType
count          80
unique          2
top     Hatchback
freq           50

In [133]:
data['CarType'].value_counts()

Hatchback    50
SUV          30
Name: CarType, dtype: int64

In [138]:
data['IntI']

0     2.86
1     9.72
2    -7.61
3     0.92
4    -4.15
5     0.83
6    -6.65
7    -6.85
8     8.10
9     0.27
10   -4.68
11   -6.06
12   -9.38
13    7.85
14     NaN
15    5.77
16   -2.94
17   -3.68
18   -8.01
19    2.86
20   -9.99
21     NaN
22    3.70
23   -7.48
24   -7.00
25   -0.41
26    4.67
27   -1.93
28    9.36
29    0.73
      ...
50    6.23
51    6.07
52    8.48
53    2.25
54   -1.38
55    8.55
56   -7.49
57   -7.58
58    7.95
59   -0.42
60    5.41
61    5.74
62    1.57
63    8.76
64    4.02
65   -3.63
66   -7.52
67    8.38
68   -7.10
69    5.61
70   -7.98
71    9.58
72   -3.22
73    6.47
74   -7.74
75   -2.12
76   -2.65
77   -5.45
78   -2.13
79    1.57
Name: IntI, Length: 80, dtype: float64

In [139]:
data.dropna()

    CarID  ManHI  ManBI  IntI  HVACi  Safety    CarType
0       1  -5.27  -1.30  2.86  -4.85    4.04        SUV
1       2  -4.82  -5.38  9.72  -0.97   -4.57  Hatchback
2       3   9.57  -7.50 -7.61   1.33   -5.10  Hatchback
3       4   2.84  -2.85  0.92   5.51   -6.64  Hatchback
4       5   0.00   2.68 -4.15   0.85    5.58        SUV
5       6   0.40   6.34  0.83   5.03   -8.10        SUV
6       7   5.94   3.14 -6.65   6.62   -1.32  Hatchback
7       8   5.78  -1.75 -6.85   0.73    5.50  Hatchback
8       9   0.86  -4.32  8.10  -8.96    3.10  Hatchback
9      10   7.36   7.42  0.27  -8.62    3.08        SUV
10     11  -7.95  -6.44 -4.68   3.86    9.82  Hatchback
11     12  -1.75  -8.09 -6.06  -9.13   -6.45        SUV
12     13   9.44  -0.02 -9.38   0.06    6.06        SUV
13     14  -9.67   9.61  7.85   5.88   -8.14  Hatchback
15     16  -9.93  -6.15  5.77   8.76    3.60  Hatchback
16     17   3.16  -6.80 -2.94   1.83    8.36  Hatchback
17     18   5.36  -9.77 -3.68  -4.68    0.87  Hatchback
18     19  -4.46   0.79 -8.01  -6.72   -5.92        SUV
19     20   7.67   3.36  2.86  -7.24    3.71        SUV
20     21   7.44   2.28 -9.99  -1.89    4.17        SUV
22     23  -3.37  -2.06  3.70  -3.10    1.95  Hatchback
23     24  -3.39  -6.65 -7.48   4.50    1.95  Hatchback
24     25  -8.94  -2.31 -7.00  -0.01    2.16        SUV
25     26   7.46  -3.80 -0.41   6.34    9.24  Hatchback
26     27   6.43  -7.24  4.67   4.75   -5.07  Hatchback
27     28   5.14  -3.78 -1.93   1.24    8.35  Hatchback
28     29  -4.42  -4.70  9.36  -0.28   -1.63  Hatchback
29     30  -1.38  -8.80  0.73  -1.77    8.60  Hatchback
30     31  -4.83  -3.30  3.50   0.60   -9.11  Hatchback
32     33  -8.32  -2.71  4.89   2.85   -5.75  Hatchback
..    ...    ...    ...   ...    ...     ...        ...
50     51   3.67  -5.75  6.23  -7.30   -5.55        SUV
51     52   1.15   6.26  6.07  -5.59   -7.95        SUV
52     53  -9.04  -4.88  8.48  -5.04    0.36  Hatchback
53     54   2.67  -1.87  2.25  -1.47    0.36  Hatchback
54     55   0.64  -0.62 -1.38   1.54    0.79  Hatchback
55     56   5.00  -6.63  8.55  -6.58   -0.06  Hatchback
56     57  -0.97   9.52 -7.49   1.19   -0.10        SUV
57     58  -8.87  -9.94 -7.58  -6.41    4.85        SUV
58     59   5.76  -0.49  7.95  -6.07    2.35  Hatchback
59     60  -8.26  -1.36 -0.42   5.99   -3.12  Hatchback
60     61  -6.28  -1.76  5.41   5.32    4.91  Hatchback
61     62  -6.14   8.41  5.74   2.55    2.56  Hatchback
62     63  -7.07  -5.69  1.57   8.32   -2.04  Hatchback
63     64  -6.40  -2.63  8.76   3.79    2.40  Hatchback
64     65   2.06   7.81  4.02  -8.90   -0.76        SUV
65     66  -6.78   3.59 -3.63   7.95    9.13  Hatchback
66     67   3.53   7.81 -7.52  -5.93   -5.00        SUV
67     68  -1.67  -8.72  8.38   3.73    4.43  Hatchback
68     69  -9.07  -2.77 -7.10  -9.82   -1.21        SUV
69     70  -9.62  -0.05  5.61   9.89   -0.25  Hatchback
70     71  -5.44   0.33 -7.98   7.53    9.54  Hatchback
71     72   4.88  -1.99  9.58  -1.43   -8.76  Hatchback
72     73   0.63  -1.11 -3.22   6.66    7.72  Hatchback
73     74   6.49  -6.03  6.47  -8.21   -8.32        SUV
74     75   0.78   5.21 -7.74   9.78    1.41  Hatchback
75     76   2.92   7.36 -2.12   4.09    9.91  Hatchback
76     77  -3.93  -0.21 -2.65   3.57   -8.16        SUV
77     78   0.88  -3.76 -5.45   0.62    0.67        SUV
78     79   3.30   4.37 -2.13   8.45   -7.41  Hatchback
79     80   5.02  -7.54  1.57  -2.31    9.99  Hatchback

[77 rows x 7 columns]

In [140]:
#gives correlation
data.corr()

           CarID     ManHI     ManBI      IntI     HVACi    Safety
CarID   1.000000 -0.145632  0.107529  0.076919  0.106891  0.011986
ManHI  -0.145632  1.000000  0.081582 -0.087643 -0.164935  0.018466
ManBI   0.107529  0.081582  1.000000 -0.096270  0.143497 -0.122126
IntI    0.076919 -0.087643 -0.096270  1.000000 -0.098272 -0.155162
HVACi   0.106891 -0.164935  0.143497 -0.098272  1.000000  0.020642
Safety  0.011986  0.018466 -0.122126 -0.155162  0.020642  1.000000

In [142]:
data["CarType"].value_counts()

Hatchback    50
SUV          30
Name: CarType, dtype: int64

In [141]:
#converts categorical data dummy variable
pd.get_dummies(data,columns=["CarType"])

    CarID  ManHI  ManBI  IntI  HVACi  Safety  CarType_Hatchback  CarType_SUV
0       1  -5.27  -1.30  2.86  -4.85    4.04                  0            1
1       2  -4.82  -5.38  9.72  -0.97   -4.57                  1            0
2       3   9.57  -7.50 -7.61   1.33   -5.10                  1            0
3       4   2.84  -2.85  0.92   5.51   -6.64                  1            0
4       5   0.00   2.68 -4.15   0.85    5.58                  0            1
5       6   0.40   6.34  0.83   5.03   -8.10                  0            1
6       7   5.94   3.14 -6.65   6.62   -1.32                  1            0
7       8   5.78  -1.75 -6.85   0.73    5.50                  1            0
8       9   0.86  -4.32  8.10  -8.96    3.10                  1            0
9      10   7.36   7.42  0.27  -8.62    3.08                  0            1
10     11  -7.95  -6.44 -4.68   3.86    9.82                  1            0
11     12  -1.75  -8.09 -6.06  -9.13   -6.45                  0            1
12     13   9.44  -0.02 -9.38   0.06    6.06                  0            1
13     14  -9.67   9.61  7.85   5.88   -8.14                  1            0
14     15   6.81   3.66   NaN   0.89   -2.41                  1            0
15     16  -9.93  -6.15  5.77   8.76    3.60                  1            0
16     17   3.16  -6.80 -2.94   1.83    8.36                  1            0
17     18   5.36  -9.77 -3.68  -4.68    0.87                  1            0
18     19  -4.46   0.79 -8.01  -6.72   -5.92                  0            1
19     20   7.67   3.36  2.86  -7.24    3.71                  0            1
20     21   7.44   2.28 -9.99  -1.89    4.17                  0            1
21     22   2.03  -5.81   NaN  -6.47    9.79                  1            0
22     23  -3.37  -2.06  3.70  -3.10    1.95                  1            0
23     24  -3.39  -6.65 -7.48   4.50    1.95                  1            0
24     25  -8.94  -2.31 -7.00  -0.01    2.16                  0            1
25     26   7.46  -3.80 -0.41   6.34    9.24                  1            0
26     27   6.43  -7.24  4.67   4.75   -5.07                  1            0
27     28   5.14  -3.78 -1.93   1.24    8.35                  1            0
28     29  -4.42  -4.70  9.36  -0.28   -1.63                  1            0
29     30  -1.38  -8.80  0.73  -1.77    8.60                  1            0
..    ...    ...    ...   ...    ...     ...                ...          ...
50     51   3.67  -5.75  6.23  -7.30   -5.55                  0            1
51     52   1.15   6.26  6.07  -5.59   -7.95                  0            1
52     53  -9.04  -4.88  8.48  -5.04    0.36                  1            0
53     54   2.67  -1.87  2.25  -1.47    0.36                  1            0
54     55   0.64  -0.62 -1.38   1.54    0.79                  1            0
55     56   5.00  -6.63  8.55  -6.58   -0.06                  1            0
56     57  -0.97   9.52 -7.49   1.19   -0.10                  0            1
57     58  -8.87  -9.94 -7.58  -6.41    4.85                  0            1
58     59   5.76  -0.49  7.95  -6.07    2.35                  1            0
59     60  -8.26  -1.36 -0.42   5.99   -3.12                  1            0
60     61  -6.28  -1.76  5.41   5.32    4.91                  1            0
61     62  -6.14   8.41  5.74   2.55    2.56                  1            0
62     63  -7.07  -5.69  1.57   8.32   -2.04                  1            0
63     64  -6.40  -2.63  8.76   3.79    2.40                  1            0
64     65   2.06   7.81  4.02  -8.90   -0.76                  0            1
65     66  -6.78   3.59 -3.63   7.95    9.13                  1            0
66     67   3.53   7.81 -7.52  -5.93   -5.00                  0            1
67     68  -1.67  -8.72  8.38   3.73    4.43                  1            0
68     69  -9.07  -2.77 -7.10  -9.82   -1.21                  0            1
69     70  -9.62  -0.05  5.61   9.89   -0.25                  1            0
70     71  -5.44   0.33 -7.98   7.53    9.54                  1            0
71     72   4.88  -1.99  9.58  -1.43   -8.76                  1            0
72     73   0.63  -1.11 -3.22   6.66    7.72                  1            0
73     74   6.49  -6.03  6.47  -8.21   -8.32                  0            1
74     75   0.78   5.21 -7.74   9.78    1.41                  1            0
75     76   2.92   7.36 -2.12   4.09    9.91                  1            0
76     77  -3.93  -0.21 -2.65   3.57   -8.16                  0            1
77     78   0.88  -3.76 -5.45   0.62    0.67                  0            1
78     79   3.30   4.37 -2.13   8.45   -7.41                  1            0
79     80   5.02  -7.54  1.57  -2.31    9.99                  1            0

[80 rows x 8 columns]

In [179]:
#any(axis=1) checks for whether there is any null value in columns or not
data.isnull().any(axis=1).sum()

3

In [147]:
data.dropna(inplace=True)

In [149]:
data.isnull().any(axis=1).sum()

0

In [154]:
data1=pd.get_dummies(data,columns=["CarType"])

In [160]:
data1.dtypes

CarID                  int64
ManHI                float64
ManBI                float64
IntI                 float64
HVACi                float64
Safety               float64
CarType_Hatchback      uint8
CarType_SUV            uint8
dtype: object

In [156]:
column_list=list(data.columns)

In [157]:
features=list(set(column_list)-set(['CarType']))

In [161]:
y=data[['CarType']]

In [163]:
x=data[features]

In [164]:
y.shape

(77, 1)

In [165]:
x.shape

(77, 6)

In [166]:
pd.get_dummies(y,columns=["CarType"])

    CarType_Hatchback  CarType_SUV
0                   0            1
1                   1            0
2                   1            0
3                   1            0
4                   0            1
5                   0            1
6                   1            0
7                   1            0
8                   1            0
9                   0            1
10                  1            0
11                  0            1
12                  0            1
13                  1            0
15                  1            0
16                  1            0
17                  1            0
18                  0            1
19                  0            1
20                  0            1
22                  1            0
23                  1            0
24                  0            1
25                  1            0
26                  1            0
27                  1            0
28                  1            0
29                  1            0
30                  1            0
32                  1            0
..                ...          ...
50                  0            1
51                  0            1
52                  1            0
53                  1            0
54                  1            0
55                  1            0
56                  0            1
57                  0            1
58                  1            0
59                  1            0
60                  1            0
61                  1            0
62                  1            0
63                  1            0
64                  0            1
65                  1            0
66                  0            1
67                  1            0
68                  0            1
69                  1            0
70                  1            0
71                  1            0
72                  1            0
73                  0            1
74                  1            0
75                  1            0
76                  0            1
77                  0            1
78                  1            0
79                  1            0

[77 rows x 2 columns]

In [171]:
test_x=Test_Data[['CarID', 'ManHI', 'ManBI', 'IntI', 'HVACi', 'Safety']]

In [172]:
test_y=Test_Data[['CarType']]

In [173]:
prediction=knn.predict(test_x)

In [174]:
prediction

array(['Hatchback', 'Hatchback', 'Hatchback', 'Hatchback', 'Hatchback',
       'Hatchback', 'Hatchback', 'Hatchback', 'Hatchback', 'Hatchback',
       'Hatchback', 'Hatchback', 'Hatchback', 'Hatchback', 'Hatchback',
       'Hatchback', 'Hatchback', 'Hatchback', 'Hatchback', 'Hatchback'],
      dtype=object)

In [175]:
pd.get_dummies(test_y,columns=['CarType'])

    CarType_Hatchback  CarType_SUV
0                   1            0
1                   0            1
2                   1            0
3                   1            0
4                   1            0
5                   1            0
6                   0            1
7                   0            1
8                   0            1
9                   0            1
10                  0            1
11                  1            0
12                  0            1
13                  0            1
14                  0            1
15                  0            1
16                  1            0
17                  1            0
18                  1            0
19                  1            0

In [176]:
ac=accuracy_score(test_y,prediction)

In [177]:
ac

0.5